version: "3.8"

services:
  device_control:
    build: .
    ports:
      - "8010:8010"
    depends_on:
      - mqtt
      - mongodb

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
