version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot_data
      MYSQL_USER: iot
      MYSQL_PASSWORD: iot123
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt_server/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

  fastapi-backend:
    build:
      context: ./fastapi_backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - mysql
      - redis
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mqtt-to-kafka:
    build:
      context: ./mqtt_to_kafka
    container_name: mqtt_to_kafka
    env_file:
      - ./mqtt_to_kafka/.env
    depends_on:
      - kafka
      - mqtt
      - fastapi-backend
    # QUAN TRỌNG: restart on-failure sẽ tự động retry khi crash
    # Kết hợp với retry logic trong code Python
    restart: on-failure:10
    environment:
      KAFKA_BROKER: kafka:29092
      MQTT_BROKER: mqtt
      MQTT_PORT: 1883
      ROOM_API_BASE: http://fastapi_backend:8000

  spark-processor:
    build:
      context: ./spark_jobs
    container_name: spark_processor
    depends_on:
      - kafka
      - mongodb
      - mysql
    restart: unless-stopped
    environment:
      SPARK_HOME: /opt/spark
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MONGODB_URI: mongodb://mongodb:27017/
    volumes:
      - spark-checkpoint:/opt/spark/work-dir

  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - mongodb

volumes:
  mongodb-data:
    driver: local
  mysql-data:
    driver: local
  mosquitto-data:
    driver: local
  mosquitto-logs:
    driver: local
  grafana-storage:
    driver: local
  spark-checkpoint:
    driver: local