version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"  # WebSocket port (optional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
